CREATE TABLE IF NOT EXISTS properties (
  id                  VARCHAR(36)    PRIMARY KEY,
  listing_type        VARCHAR(10)    NOT NULL,
  property_type       VARCHAR(50)    NOT NULL,
  listed_by           VARCHAR(20)    NOT NULL,
  title               VARCHAR(255)   NOT NULL,
  description         TEXT           NOT NULL,
  price               DECIMAL(15,2)  NOT NULL,
  rent_per_month      DECIMAL(15,2)  NULL,
  security_deposit    DECIMAL(15,2)  NULL,
  maintenance_charges DECIMAL(15,2)  NULL,
  negotiable          BOOLEAN        NOT NULL DEFAULT FALSE,
  city                VARCHAR(100)   NOT NULL,
  locality            VARCHAR(100)   NOT NULL,
  project_name        VARCHAR(255)   NULL,
  full_address        TEXT           NULL,
  landmark            VARCHAR(255)   NULL,
  pincode             VARCHAR(10)    NULL,
  lat                 DECIMAL(10,7)  NULL,
  lng                 DECIMAL(10,7)  NULL,
  built_up_area       INT            NOT NULL,
  carpet_area         INT            NULL,
  bedrooms            INT            NULL,
  bathrooms           INT            NULL,
  balconies           INT            NULL,
  floor               INT            NULL,
  total_floors        INT            NULL,
  facing              VARCHAR(20)    NULL,
  furnishing          VARCHAR(30)    NOT NULL,
  parking             VARCHAR(10)    NOT NULL,
  property_age        VARCHAR(20)    NOT NULL,
  availability_date   DATE           NULL,
  possession_status   VARCHAR(30)    NOT NULL,
  amenities           JSON           NOT NULL DEFAULT (JSON_ARRAY()),
  featured_image      VARCHAR(500)   NOT NULL,
  gallery_images      JSON           NOT NULL DEFAULT (JSON_ARRAY()),
  video_url           VARCHAR(500)   NULL,
  contact_name        VARCHAR(100)   NOT NULL,
  contact_phone       VARCHAR(20)    NOT NULL,
  contact_email       VARCHAR(100)   NULL,
  prefer_whatsapp     BOOLEAN        NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);
